<?php

namespace App\Enums;

enum AuditAction: string
{
    case CASE_CREATED = 'CASE_CREATED';
    case CASE_STATE_CHANGED = 'CASE_STATE_CHANGED';
    case PARTY_CREATED = 'PARTY_CREATED';
    case AUDIO_CAPTURED = 'AUDIO_CAPTURED';
    case TRANSCRIPT_GENERATED = 'TRANSCRIPT_GENERATED';
    case CLAIM_EXTRACTED = 'CLAIM_EXTRACTED';
    case CRITICAL_FIELD_FLAGGED = 'CRITICAL_FIELD_FLAGGED';
    case CRITICAL_FIELD_CONFIRMED = 'CRITICAL_FIELD_CONFIRMED';
    case CRITICAL_FIELD_CORRECTED = 'CRITICAL_FIELD_CORRECTED';
    case CRITICAL_FIELD_UNRESOLVED = 'CRITICAL_FIELD_UNRESOLVED';
    case ISSUE_GRAPH_GENERATED = 'ISSUE_GRAPH_GENERATED';
    case ISSUE_OVERRIDDEN_BY_MEDIATOR = 'ISSUE_OVERRIDDEN_BY_MEDIATOR';
    case CLAIM_CORRECTED_BY_MEDIATOR = 'CLAIM_CORRECTED_BY_MEDIATOR';
    case CASE_PACKET_CREATED = 'CASE_PACKET_CREATED';
    case CASE_DELETED = 'CASE_DELETED';
    case BENCHMARK_RUN_STARTED = 'BENCHMARK_RUN_STARTED';
    case BENCHMARK_RUN_COMPLETED = 'BENCHMARK_RUN_COMPLETED';
}
